version: '3'

services:
  webserver:
    image: chandlervs/apache-php
    ports:
      - 80:80
    env_file:
      - .env
  mysql:
    image: mysql:5.7
    volumes:
      - inv-data:/var/lib/mysql
    env_file:
      - .env

volumes:
  inv-data:
